### ISSUE TITLE
Wrong image

### ISSUE THREAD

**Issue by Beercow** [EZToolsManuals/EZToolsManuals#45]
Registry Explorer help page shows picture of plugins instead of the legend.
![image](https://user-images.githubusercontent.com/10360919/205066077-abf401ed-1a83-4261-aec5-d392a5f6514a.png)

**Comment by AndrewRathbun** [comment]
Turns out I had quite a few issues going on in that chapter. @Beercow thank you again and a new version has been pushed out. It *should* be fixed now
