### ISSUE TITLE
Timeline Explorer - Sorting numbers out of order

### ISSUE THREAD

**Issue by SchlesHammer** [EZToolsManuals/EZToolsManuals#50]
When sorting a column containing numbers/integers, the sorting is being done by the first digit, instead of the whole number.

![image](https://user-images.githubusercontent.com/85708703/214082665-ef1fdf4e-d4b6-4571-bb4d-ce6dfafaab5c.png)

**Comment by AndrewRathbun** [comment]
This is because you're likely ingesting output that doesn't have TLE Plugin available, correct?

**Comment by EricZimmerman** [comment]
Yes thats because all generic Csvs treat everything as a string. 

No other way to do it except add support for that particular kind of file

**Comment by AndrewRathbun** [comment]
https://github.com/EricZimmerman/TLEFilePlugins is the repo where plugins can be pushed to. Closing this issue for the time being.

**Comment by SchlesHammer** [comment]
Got it, thanks so much!
