### ISSUE TITLE
MFTEcmd Parent Sequence number output is signed

### ISSUE THREAD

**Issue by ydkhatri** [EZToolsManuals/EZToolsManuals#55]
The 2 bytes representing sequence numbers are treated differently depending on field in the output of MFTEcmd. 
When reading an entry, the sequence number is interpreted as Unsigned, however when reading the two bytes for Parent Sequence number, they are interpreted as Signed, at least in the output. Hence sometimes the parent sequence number becomes negative, while the sequence number is always positive. 

It appears that the anomaly is only upon output, internally it uses the same type (for both) to correctly match up the numbers and compute the Parent Paths for each entry.

See the sample output from MFTEcmd below, where 0x9387 is interpreted differently in the two fields.

|EntryNumber|SequenceNumber|InUse|ParentEntryNumber|ParentSequenceNumber|ParentPath|
|-------------|------------------|----|------------------|---------------|---------------|
|848|37767|True|329444|100|.\ProgramData\xx\LocalSystem\Python|
|866|9030|True|848|**-27769**|.\ProgramData\xx\LocalSystem\Python\payload|

_Resolution_ - The parent sequence number must also be treated as an unsigned number.

**Comment by AndrewRathbun** [comment]
@EricZimmerman want this transferred to MFT, MFTECmd, Issues, or keep it here?

**Comment by EricZimmerman** [comment]
This is fine. I'll get this today.

**Comment by EricZimmerman** [comment]
this is an odd place to open the issue tho @AndrewRathbun  =)

**Comment by EricZimmerman** [comment]
@ydkhatri if you can redownload and verify, please confirm the fix

**Comment by ydkhatri** [comment]
Thanks for the quick fix. I'll check it shortly.

Apologies for putting this in the wrong place, in a hurry I clicked on some link on your site that brought me here, saw another MFTEcmd issue and just added mine..

**Comment by ydkhatri** [comment]
Thanks, this was fixed, however now TimelineExplorer would not load the output file as it still expects a signed value (**System.Int16**). This needs a fix too, I think it's coming from one of the plugin DLLs.
```
2024-03-11 04:57:56 [Error]: Error processing "C:\...\20240311001409_MFTECmd_$MFT_Output.csv": "The conversion cannot be performed.    Text: '37767'    MemberName: ParentSequenceNumber    MemberType: System.Nullable`1[[System.Int16, System.Private.CoreLib, ...
```
